//
// Created by Or on 12/14/2023.
//

#ifndef CPP_PLAYGROUND_FREESTANDINGREFERENCES_H
#define CPP_PLAYGROUND_FREESTANDINGREFERENCES_H


void showFreeStandingReferenceDemo();


#endif //CPP_PLAYGROUND_FREESTANDINGREFERENCES_H
