//
// Created by Or on 12/26/2023.
//

#ifndef CPP_PLAYGROUND_STATICHIERARCHYNAVIGATION_H
#define CPP_PLAYGROUND_STATICHIERARCHYNAVIGATION_H


void testStaticHierarchyNavigation();


#endif //CPP_PLAYGROUND_STATICHIERARCHYNAVIGATION_H
