//
// Created by Or on 12/26/2023.
//

#ifndef CPP_PLAYGROUND_OPERATORPOLYMORPHISM_H
#define CPP_PLAYGROUND_OPERATORPOLYMORPHISM_H


void testOperatorPolymorphism();


#endif //CPP_PLAYGROUND_OPERATORPOLYMORPHISM_H
