//
// Created by Or on 12/23/2023.
//

#ifndef CPP_PLAYGROUND_COPYCONSTRUCTORUPCASTINGDEMO_H
#define CPP_PLAYGROUND_COPYCONSTRUCTORUPCASTINGDEMO_H


void testCCUpCastingDemo();


#endif //CPP_PLAYGROUND_COPYCONSTRUCTORUPCASTINGDEMO_H
