//
// Created by Or on 12/23/2023.
//

#ifndef CPP_PLAYGROUND_PRIVATEINHERITANCE_H
#define CPP_PLAYGROUND_PRIVATEINHERITANCE_H


void testPrivateInheritance();


#endif //CPP_PLAYGROUND_PRIVATEINHERITANCE_H
